"""make chunk embedding nullable

Revision ID: 4d9443a4a886
Revises: d7dd7cd84067
Create Date: 2026-07-18 22:36:35.219716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9443a4a886'
down_revision: Union[str, Sequence[str], None] = 'd7dd7cd84067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_chunks")as batch_op:
        batch_op.alter_column('embedding_json',
               existing_type=sa.TEXT(),
               nullable=True
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_chunks") as batch_op:
        batch_op.alter_column('embedding_json',
               existing_type=sa.TEXT(),
               nullable=False
               )
    # ### end Alembic commands ###
